### ISSUE TITLE
KeyError: 'controllerType=0 controllerNumber=1 scan=00586'

### ISSUE THREAD

**Issue by BenSamy2020** [lisavetasol/viQC#1]
Greetings,

I am a new user for this tool. I am in the process of trying out your tool for QC purposes. I am hitting an error (error message provided below. Additionally, the input files can be downloaded from: https://drive.google.com/file/d/1TxCqj6uyE8MrcmJTQJBWTIHE6FWymUc9/view?usp=sharing. Please do advise me on how to troubleshoot this error.

Regards,
Ben 

C:\Users\parth\viQC>viQC D:\Python_Input_Files\psm.mzML -refFile D:\Python_Input_Files\psm.mzML -refPSM D:\MSFragger_Temp\viQC\viQC_Output\psm.csv -cn Spectrum -d ,
   INFO: [06:51:26] Reading data for psm...
   INFO: [06:51:39] Reading reference files for angle score calculation...
Traceback (most recent call last):
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\pyteomics\xml.py", line 1130, in get_by_id
    offset, element_type = index.find_no_type(elem_id)
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\pyteomics\auxiliary\file_helpers.py", line 823, in find_no_type
    raise KeyError(key)
KeyError: 'controllerType=0 controllerNumber=1 scan=00586'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\parth\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\parth\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\parth\AppData\Local\Programs\Python\Python39\Scripts\viQC.exe\__main__.py", line 7, in <module>
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\viqc\viQC.py", line 771, in main
    process_file(infile, args)
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\viqc\viQC.py", line 589, in process_file
    mz_ms2, angle_x, angle_y, prec_int, prec_isolated_mz, x, y, coef = read_data(
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\viqc\viQC.py", line 166, in read_data
    sc = f[id_format.format(sc_number)]
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\pyteomics\auxiliary\file_helpers.py", line 283, in __getitem__
    return self.get_by_id(key)
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\pyteomics\auxiliary\file_helpers.py", line 84, in wrapped
    return func(self, *args, **kwargs)
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\pyteomics\xml.py", line 1138, in get_by_id
    elem = self._find_by_id_reset(elem_id, id_key=id_key)
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\pyteomics\auxiliary\file_helpers.py", line 84, in wrapped
    return func(self, *args, **kwargs)
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\pyteomics\xml.py", line 1105, in _find_by_id_reset
    return self._find_by_id_no_reset(elem_id, id_key=id_key)
  File "c:\users\parth\appdata\local\programs\python\python39\lib\site-packages\pyteomics\xml.py", line 649, in _find_by_id_no_reset
    raise KeyError(elem_id)
KeyError: 'controllerType=0 controllerNumber=1 scan=00586'

**Comment by levitsky** [comment]
Hi @BenSamy2020, this was a bug in viQC which affected spectrum name matching between reference PSMs and mzML. As you can see the spectrum titles are not the same as spectrum IDs in mzML, and there was an error when trying to match them. I pushed a change that should fix it, sorry for the inconvenience.

I am not the author of viQC and I don't know it very well, but let me make a couple of comments based on what I know/believe:

1. Using a reference file is optional. It only adds "angle score" on the last figure in the output. The rest you can get by just running `viQC my.mzML`.
2. The reference file is supposed to be some "gold standard" run that you know is good (a lot of PSMs, etc.). Using the same file as reference and as input will not be very informative, the angle score will always be high.

Edit: sorry, I accidentally pushed the fix to the wrong repo... I will update the current repo shortly.

**Comment by BenSamy2020** [comment]
Greetings @levitsky,

You're a champion. Thanks alot for all the support you have provided over github. Once, update, please do let me know.
Thank you.

Regards,
Ben

**Comment by levitsky** [comment]
Always happy to help, @BenSamy2020 :)
I pushed the fix, sorry for the delay.

Also, note that you can run viQC with many files at once, and get batch plots where it's easy to notice outlier runs.

**Comment by BenSamy2020** [comment]
Greetings @levitsky,

Just to update you, I have successfully ran the package and it is working. But there was a notification of "File names for angle score calibration don't match!".

Maybe you might want to remove that warning.

Regards,
Ben

![image](https://user-images.githubusercontent.com/69944967/163079352-84e9ed5b-56f5-488f-81ad-dc3526477a98.png)
